---
- name: Copying the file to remote
  hosts: all

  tasks:
    - name: Copy files
      copy:
        src: /root/myfile.txt
        dest: /tmp/
        onwer: paul
        group: paul
        mode: ugo=rw