help: ## Print this message
	@fgrep -h "##" $(MAKEFILE_LIST) | fgrep -v fgrep | sed -e 's/\\$$//' | sed -e 's/##//'
frontend:   ## Install Frontend Component
	@echo Installing Frontend
catalogue:  ## Install Catalogue Component
	@echo Installing Catalogue
cart:       ## Install Cart Component
	@echo Installing Cart
user:       ## Install USer Component
	@echo Installing User
shipping:   ## Install Shipping Component
	@echo Installing Shipping
payment:    ## Install Payment Component
	@echo Installing Payment
mongodb:    ## Install MongoDB Component
	@echo Installing MongoDB
redis:      ## Install Redis Component
	@echo Installing Redis
mysql:      ## Install MYSQL Component
	@echo Installing MYSQL
rabbitMQ:   ## Install RabbitMQ Component
	@echo Installing RabbitMQ

